POST {{host}}/events
Content-Type: application/json

{
  "appKey": "1071ef1f-62b9-41cc-a443-124c1a80e202",
  "type": "Event {{$randomInt}}",
  "properties": {}
}

###
POST {{host}}/apps
Content-Type: application/json

{
  "name": "App {{$randomInt}}"
}

###
