version: '3'

services:
  postgres:
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  redis:
    image: 'redis:6-alpine'
    ports:
      - ${REDIS_PORT:-6379}:6379
